#!/bin/bash

# set -e

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT

# direct all logs to application-stop.log
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/home/ubuntu/agilityup-backend-logs/application-stop.log 2>&1

# stop nginx webserver
sudo /bin/bash -c "systemctl stop nginx.service"
